sudo: false
language: node_js
notifications:
  email: false
cache:
  directories:
    - node_modules
node_js:
  - node
  - lts/*
install:
  - npm install -g codecov
  - npm install
before_script:
  - npm prune
script:
  - npm run test
  - codecov
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
