sudo: false
language: node_js
notifications:
  email: false
cache:
  directories:
    - node_modules
node_js:
  - v6
  - v5
  - v4
script:
  - npm run test
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
