sudo: false
language: node_js
notifications:
  email: false
node_js:
  - v5
  - v4
  - iojs-v3
  - '0.12'
  - '0.10'
script:
  - npm run test
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'		
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
