sudo: false
language: node_js
notifications:
  email: false
cache:
  directories:
    - node_modules
node_js:
  - node
  - lts/*
install:
  - npm install -g codecov
  - npm install
before_script:
  - npm prune
script:
  - npm run test
  - codecov
after_success:
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
